changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - type:breaking-change
    - title: New capabilities
      labels:
        - type:feature
    - title: Fixes
      labels:
        - type:bug
    - title: Documentation
      labels:
        - type:docs
    - title: Internal improvements
      labels:
        - type:refactor
        - type:chore
    - title: Other changes
      labels:
        - "*"
